package com.soft.email;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.Date;
import java.util.Properties;
import java.io.*;

import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.sax.SAXResult;
import javax.xml.transform.stream.StreamSource;

import org.apache.log4j.Logger;

import com.soft.email.beans.*;
import com.soft.email.core.Enviornment;
import com.soft.email.db.EmailDBManager;
import com.soft.email.parser.AsciiFilter;
import com.soft.email.parser.WhiteSpaceFilter;
import com.soft.email.parser.Xml2Text;
public class DataInconsistencyEmails {
	
	private static final Logger log = Logger.getLogger(EmailManager.class);
	EmailDBManager sdb = null;
    Enviornment env;
    EmailSender emailSender = null;
    String ApplicationName="DataInconsistencyEmail" ;
    	
	public 	DataInconsistencyEmails(Enviornment env){
		this.env = env;
	}
	
	
	public  static void main( String argv[]) throws IOException , Exception
	{
		try{
			if (argv[0] == null || argv[0].length() == 0) {
				argv[0] = "./";
			}
		}catch(Exception et){
			argv = new String[1];
			argv[0] = "./";
		}
		
		
	    Enviornment env = Enviornment.getEnviornment(argv[0]);
	    DataInconsistencyEmails die = new DataInconsistencyEmails(Enviornment.getEnviornment(argv[0]));	
	    
	   	System.out.println("Inconsistant CDR Data sent : "+die.sendInconsistentCDRDataEmail());
	   	System.out.println("Program is ended.............. ");
	    
	   	
	}
	
	public boolean sendInconsistentCDRDataEmail() throws IOException , Exception
	{
		boolean isSuccess=false;
		
		int NoOfEmail = 0;
		while (NoOfEmail < 2 ){
			NoOfEmail++;
			if (NoOfEmail == 1){
				Email email = InconsistentCDRDataEmail(2, 3, false);
				//InconsistentCDRDataEmail(int NE_ElementID, boolean isIncoming, boolean isZeroDur)
			    if (email != null){
			    	Properties sysProperties = System.getProperties();
				    sysProperties.put("mail.smtp.host", env.getEMAIL_SERVER());
				    sysProperties.put("mail.smtp.auth", "true");
				    EmailSender eSender = new EmailSender(sysProperties, env.getEMAIL_SERVER(), env.getServerUserName(), env.getServerPassword());
			    	isSuccess = eSender.sendEmail(this.ApplicationName, email );
			    }
			}else if (NoOfEmail == 2){
				Email email = InconsistentCDRDataEmail(2, 3, true);
			    if (email != null){
			    	Properties sysProperties = System.getProperties();
				    sysProperties.put("mail.smtp.host", env.getEMAIL_SERVER());
				    sysProperties.put("mail.smtp.auth", "true");
				    EmailSender eSender = new EmailSender(sysProperties, env.getEMAIL_SERVER(), env.getServerUserName(), env.getServerPassword());
			    	isSuccess = eSender.sendEmail(this.ApplicationName, email );
			    }
			}
		}
	    return isSuccess;
	}
	//Carrier Type 1=incoming, 2=outgoing 3 for both
	public Email InconsistentCDRDataEmail(int NE_ElementID, int CarrierType, boolean isZeroDur) throws IOException , Exception
	{
	   		Connection conn=null;
	      	ResultSet rs=null;
	      	Statement stmt=null;
	      	String sql="";
	      	Email email= new Email();
	      	EmailType emtype = new EmailType();
	      	int EMT_TypeID = 20; // fixed for carrier's miss-configured CDRs
	      	try{
	      		sdb = EmailDBManager.getDBManager(env);
	      		conn= sdb.getConnection(); 
				stmt=conn.createStatement();
				System.out.println("<br>Statement object is created successfull ");
				emtype = sdb.getEmailType(EMT_TypeID);
				System.out.println("Eamil Configuration retrived. ");
				String Message="";
				if (isZeroDur)
					Message="<html><Head><h2>CDR Inconsistency Report - CallDuration = 0</h2></Head><Body>";
				else
					Message="<html><Head><h2>CDR Inconsistency Report - CallDuration > 0</h2></Head><Body>";
				//FindMissConfiguredCDRs(Statement stmt, int NE_ElementID, boolean isIncoming, boolean isZeroDur) 
				if (CarrierType == 1)
					Message += "<br>"+FindMissConfiguredCDRs(stmt, NE_ElementID, true, isZeroDur);
				else if (CarrierType == 2)
					Message += "<br>"+FindMissConfiguredCDRs(stmt, NE_ElementID, false, isZeroDur);
				else{ 
					Message += "<br>"+FindMissConfiguredCDRs(stmt, NE_ElementID, true, isZeroDur);
					Message += "<br>"+FindMissConfiguredCDRs(stmt, NE_ElementID, false, isZeroDur);
				}
				Message += "<br>"+FindMissConfiguredCarriers(stmt);
				Message += "<br><b> This email is auto-generated by Terminus Customer Care & Billing System</b>";
				Message += "</Body></Html>";
				email.setMessage(applyStyleSheet(Message, emtype.getStyleSheet()));
				email.setSubject(emtype.getSubject());
					
				stmt.close();
				conn.close();
		 	 	
		}
		catch(SQLException ex){
			System.out.println("SQL Exception :"+ex.getMessage());
			
		}
	    catch(Exception ext){
	    	System.out.println(ext.getMessage());
	    	
		}
	       	
		return email;
	}
	
	public String FindMissConfiguredCarriers(Statement stmt) throws IOException , Exception
	{
	 		ResultSet rs=null;
	      	String sql="";
	      	String Message="";
	      	int count=0;
	      	try{
	    	 	
	    		sql = 	" SELECT MIN(SSW_DISCONNTIME) AS FirstTIME, MAX(SSW_DISCONNTIME) AS LastTIME, COUNT(SSW_VOICERECORDID) AS NOOFCOUNTS,"+ 
						" CEIL(SUM(SSW_DURATION/10)/60) AS DURATION_SES, TrunkIDS From ("+
						" SELECT SSW_DISCONNTIME, SSW_VOICERECORDID, SSW_DURATION, SSW_IC_CARRIERID AS TrunkIDS"+
						" FROM SDR_TBLSSWCDRS "+
						" WHERE SSW_VOICERECORDID IN (SELECT ICPMC_RAWCDRID FROM SDR_TBLICPMISSEDCDRS)"+
						" UNION ALL "+
						" SELECT SSW_DISCONNTIME, SSW_VOICERECORDID, SSW_DURATION, SSW_OG_CARRIERID AS TrunkIDS "+
						" FROM SDR_TBLSSWCDRS "+
						" WHERE SSW_VOICERECORDID IN (SELECT ICPMC_RAWCDRID FROM SDR_TBLICPMISSEDCDRS) "+
						" ) WHERE TrunkIDS NOT IN (SELECT PNI_IDENTIFICATIONVALUE FROM PAR_TBLPARNODEIDENTI)"+
						" GROUP BY TrunkIDS"+
						" order by TrunkIDS";
				System.out.println("SQL : "+sql);
		 		rs=stmt.executeQuery(sql);
		 		
		 		Message="<Table align=Center width=600 border=1 cellspacing=0 cellpadding=0><tr bgcolor=#A4A4FF><td colspan=6><h3>Miss-Configured Carriers</h3></td></tr>"+
						"<tr bgcolor=#A4A4FF><td width=15%>#</td><td width=15%>Carrier Trunk</td><td width=10%>Calls</td>"+
						"<td width=20%>Minutes</td><td width=20%>First Call Time</td><td width=20%>Last Call Time</td></tr>";
				
				while(rs.next()){
						count++;
						
						String FirstTIME= rs.getString("FirstTIME");
						if (FirstTIME == null ) FirstTIME="";
						String LastTIME= rs.getString("LastTIME");
						if (LastTIME == null ) LastTIME="";
						int NOOFCOUNTS= rs.getInt("NOOFCOUNTS");
						if (rs.wasNull()) NOOFCOUNTS=0;
						int CallMinutes= rs.getInt("DURATION_SES");
						if (rs.wasNull()) CallMinutes=0;
						String TrunkIDS= rs.getString("TrunkIDS");
						if (TrunkIDS == null ) TrunkIDS="";
						//System.out.println(count+" - " +TrunkIDS+ " - "+NOOFCOUNTS+" - " +CallMinutes+ " - "+FirstTIME+ " - "+LastTIME);
						Message += " <tr><td>"+count+"</td><td>"+TrunkIDS+"</td><td>"+NOOFCOUNTS+"</td><td>"+CallMinutes+"</td><td>"+FirstTIME+"</td><td>"+LastTIME+"</td></tr>";  
				}
				rs.close();
				
				if (count == 0)
					Message += " <tr><td colspan=6 >No Record Found</td></tr>";
				Message += "</Table>";
				
		}
		catch(SQLException ex){
			System.out.println("SQL Exception :"+ex.getMessage());
		}
	    catch(Exception ext){
	    	System.out.println(ext.getMessage());
		}
	       	
		return Message;
	}
	
	
	public String FindMissConfiguredCDRs(Statement stmt, int NE_ElementID, boolean isIncoming, boolean isZeroDur) throws IOException , Exception
	{
	 		ResultSet rs=null;
	      	String sql="";
	      	String Message="";
	      	int count=0;
	      	try{
	    	 	
	      		if (isIncoming){
	      			
	      			sql = " select SSW_IC_CArrierID, SSW_OG_CarrierID, icppe.icppe_errordescription,CalledPrefix, FirstCall, LastCall, NoOfCalls , CallTime from "+
	      				  " ( select  SSW_IC_CArrierID, SSW_OG_CarrierID, icpmc_icerrorcode,   "+
	      				  "	 substr(SSW_TXCalledNum,1,3) as CalledPrefix, min(SSW_DisconnTime) as FirstCall, max(SSW_DisconnTime) as LastCall,"+  
	      				  "	 count(SSW_VoiceREcordID) as NoOfCalls, ceil((Sum(SSW_Duration)/10)/60) as CallTime "+
	      				  "	 from SDR_TblSSWCDRs A, sdr_tblicpmissedcdrs B  "+
	      				  "	 where a.SSW_VoiceRecordID = b.icpmc_cdrid and icpmc_icerrorcode > 0  ";
	      				  
	      				if (NE_ElementID > 0)
							sql += " and b.NE_ElementID= "+NE_ElementID;
						if (isZeroDur)
							sql += " and a.SSW_Duration = 0 ";
						else
							sql += " and a.SSW_Duration > 0 ";
	      				  
	      			sql +="	 group by  SSW_IC_CArrierID, SSW_OG_CarrierID , icpmc_icerrorcode, substr(SSW_TXCalledNum,1,3) "+
	      				  "	) e left join sdr_tblicpparsingerrors icppe on e.icpmc_icerrorcode = icppe.icppe_errorcode  "+
	      				  "	order by LastCall, icppe_errordescription, SSW_IC_CArrierID, SSW_OG_CarrierID ";
		    		
	      		}else{

	      			sql = " select SSW_IC_CArrierID, SSW_OG_CarrierID, icppe.icppe_errordescription,CalledPrefix, FirstCall, LastCall, NoOfCalls , CallTime from "+
	      				  " ( select  SSW_IC_CArrierID, SSW_OG_CarrierID, icpmc_ogerrorcode,   "+
	      				  "	 substr(SSW_TXCalledNum,1,3) as CalledPrefix, min(SSW_DisconnTime) as FirstCall, max(SSW_DisconnTime) as LastCall,"+  
	      				  "	 count(SSW_VoiceREcordID) as NoOfCalls, ceil((Sum(SSW_Duration)/10)/60) as CallTime "+
	      				  "	 from SDR_TblSSWCDRs A, sdr_tblicpmissedcdrs B  "+
	      				  "	 where a.SSW_VoiceRecordID = b.icpmc_cdrid and icpmc_ogerrorcode > 0  ";
    				  
	    				if (NE_ElementID > 0)
							sql += " and b.NE_ElementID= "+NE_ElementID;
						if (isZeroDur)
							sql += " and a.SSW_Duration = 0 ";
						else
							sql += " and a.SSW_Duration > 0 ";
    				  
	    			sql +="	 group by  SSW_IC_CArrierID, SSW_OG_CarrierID , icpmc_ogerrorcode, substr(SSW_TXCalledNum,1,3) "+
	    				  "	) e left join sdr_tblicpparsingerrors icppe on e.icpmc_ogerrorcode = icppe.icppe_errorcode  "+
	    				  "	order by LastCall, icppe_errordescription, SSW_IC_CArrierID, SSW_OG_CarrierID ";
		      			
	      		}
				System.out.println("SQL : "+sql);
		 		rs=stmt.executeQuery(sql);
		 		
					Message="<Table align=Center width=950 border=1 cellspacing=0 cellpadding=0>"+
							"<tr bgcolor=#A4A4FF><td colspan=9><h3>CDRs not Processed Due to Errors</h3></td></tr>";
					if (isIncoming){
						Message +="<tr bgcolor=#A4A4FF><td colspan=9><h4>Ingress Carriers";
					}else{
						Message +="<tr bgcolor=#A4A4FF><td colspan=9><h4>Egress Carriers";
					}
					
					if (isZeroDur){
						Message +=" - Zero Duration CDRs</h4></td></tr>";
					}else{
						Message +=" - CDRs with Duration > 0</h4></td></tr>";
					}
					
					Message +="<tr bgcolor=#A4A4FF><td width=5%>#</td>";
					Message +="<td width=8%>IC_CarrierID</td>";
					Message +="<td width=8%>OG_CarrierID</td>";
					Message +="<td width=5%>Prefix</td>";
					Message +="<td width=24%>Error</td>";
					Message +="<td width=5%>Calls</td>";
					Message +="<td width=5%>Min</td>";
					Message +="<td width=15%>First Call</td>";
					Message +="<td width=15%>Last Call</td></tr>";
					
					
				
				while(rs.next()){
						count++;
						//SSW_IC_CArrierID, SSW_OG_CarrierID, icpmc_ogerrorcode, 
						//icppe.icppe_errordescription,CalledPrefix, FirstCall, LastCall, NoOfCalls , CallTime
						String SSW_IC_CArrierID= rs.getString("SSW_IC_CArrierID");
						if (SSW_IC_CArrierID == null ) SSW_IC_CArrierID="";
						String SSW_OG_CarrierID= rs.getString("SSW_OG_CarrierID");
						if (SSW_OG_CarrierID == null ) SSW_OG_CarrierID="";
						String ErrDesc= rs.getString("icppe_errordescription");
						if (ErrDesc == null ) ErrDesc="";
						String CalledPrefix = rs.getString("CalledPrefix");
						if (CalledPrefix == null) CalledPrefix="";
						String FirstCall = rs.getString("FirstCall");
						if (FirstCall == null) FirstCall="";
						if (FirstCall.length()>17) FirstCall = FirstCall.substring(0,16);
						String LastCall = rs.getString("LastCall");
						if (LastCall == null) LastCall="";
						if (LastCall.length()>17) LastCall = LastCall.substring(0,16);
						int NoOfCalls= rs.getInt("NoOfCalls");
						if (rs.wasNull()) NoOfCalls=0;
						int CallTime= rs.getInt("CallTime");
						if (rs.wasNull()) CallTime=0;
						//System.out.println(count+" - " +YYear+ " - "+ErrDesc+" - " +NOOFCOUNTS+ " - "+CallMinutes);
						
						Message += " <tr><td>"+count+"</td>";
						Message += "<td>"+SSW_IC_CArrierID+"</td>";
						Message += "<td>"+SSW_OG_CarrierID+"</td>";
						Message += "<td>"+CalledPrefix+"</td>";
						Message += "<td>"+ErrDesc+"</td>";
						Message += "<td>"+NoOfCalls+"</td>";
						Message += "<td>"+CallTime+"</td>";  
						Message += "<td>"+FirstCall+"</td>";
						Message += "<td>"+LastCall+"</td></tr>";
						
						 
				}
				rs.close();
				if (count == 0)
					Message += " <tr><td colspan=9 >No Record Found</td></tr>";
				Message += "</Table>";
				
		}
		catch(SQLException ex){
			System.out.println("SQL Exception :"+ex.getMessage());
		}
	    catch(Exception ext){
	    	System.out.println(ext.getMessage());
		}
	       	
		return Message;
	}
	
	
	
	public String FindMissConfiguredNumbers(Statement stmt, int NE_ElementID,  boolean isZeroDur) throws IOException , Exception
	{
	 		ResultSet rs=null;
	      	String sql="";
	      	String Message="";
	      	int count=0;
	      	try{
	    	 		      			   
		    		sql = 	"   select to_Char(icpmc_EVENTTIME, 'YYYY-MM') As YYear, icpmc_CalledNumber as CalledNumber, "+ 
						 	"   count(icpmc_cdrid) as noofcdrs, ceil(sum(icpmc_callduration)/60) as CALLDURATION from sdr_tblicpmissedcdrs "+
						 	"   where (icpmc_icerrorcode in (2,3,6,7,8) or icpmc_icerrorcode in (2,3,6,7,8)) ";
						
		    		
		    		if (NE_ElementID > 0)
							sql += " and NE_ElementID= "+NE_ElementID;
						if (isZeroDur)
							sql += " and icpmc_callduration = 0 ";
						else
							sql += " and icpmc_callduration > 0 ";
						
						sql +=	"   group by to_Char(icpmc_EVENTTIME, 'YYYY-MM') ,icpmc_CalledNumber "+
							 	"   order by YYear  ";
	      		
				System.out.println("SQL : "+sql);
		 		rs=stmt.executeQuery(sql);
		 		String LastYYear="";
				
		 		
					Message="<Table align=Center width=600 border=1 cellspacing=0 cellpadding=0>"+
							"<tr bgcolor=#A4A4FF><td colspan=5><h3>CDRs not Processed Due to Errors</h3></td></tr>";
					Message +="<tr bgcolor=#A4A4FF><td colspan=5><h4>";
					if (isZeroDur){
						Message +=" - Zero Duration CDRs</h4></td></tr>";
					}else{
						Message +=" - CDRs with Duration > 0</h4></td></tr>";
					}
					
					Message +="<tr bgcolor=#A4A4FF><td width=15%>#</td><td width=15%>Yr-Mon</td><td width=40%>Called Number</td><td width=10%>Calls</td>"+
							"<td width=20%>Minutes</td></tr>";
					
				
				while(rs.next()){
						count++;
						String YYear= rs.getString("YYear");
						if (YYear == null ) YYear="";
						String CalledNumber= rs.getString("CalledNumber");
						if (CalledNumber == null ) CalledNumber="";
						int NOOFCOUNTS= rs.getInt("noofcdrs");
						if (rs.wasNull()) NOOFCOUNTS=0;
						int CallMinutes= rs.getInt("CALLDURATION");
						if (rs.wasNull()) CallMinutes=0;
						
						//System.out.println(count+" - " +YYear+ " - "+CalledNumber+" - " +NOOFCOUNTS+ " - "+CallMinutes);
						if (YYear.equalsIgnoreCase(LastYYear))
							YYear=" ";
						else
							LastYYear = YYear;
						Message += " <tr><td>"+count+"</td><td>"+YYear+"</td><td>"+CalledNumber+"</td><td>"+NOOFCOUNTS+"</td><td>"+CallMinutes+"</td></tr>";  
						 
				}
				rs.close();
				if (count == 0)
					Message += " <tr><td colspan=5 >No Record Found</td></tr>";
				Message += "</Table>";
				
		}
		catch(SQLException ex){
			System.out.println("SQL Exception :"+ex.getMessage());
		}
	    catch(Exception ext){
	    	System.out.println(ext.getMessage());
		}
	       	
		return Message;
	}
	
	

	public int insertEmail(Statement stmt, int EMT_TypeID, String EMT_FROMADDRESS, String ToEmail, String CCEmail, String EMT_Subject, String Message){
		
		int update=0;
 		try{
 			String sql = 	" INSERT INTO SS_TblEmails ( EMT_TypeID, EM_From, EM_TOList, EM_CCList, EM_Subject, EM_Message,EM_LongMESSAGE, EMS_StatusID )" +
             				" VALUES ("+EMT_TypeID+",'"+EMT_FROMADDRESS+"','"+ ToEmail+"','"+CCEmail+"','"+EMT_Subject+"','','"+Message+"',1)";
			
 			//String sql = "INSERT INTO SS_TblEmails ( EMT_TypeID, EM_From, EM_TOList, EM_CCList, EM_Subject, EM_Message,EM_LongMESSAGE, EMS_StatusID ) VALUES (20,'','','','','','<html><Head><h2>CDR Inconsistency Report</h2></Head><Body><br><Table align=Center width=600 border=1 cellspacing=0 cellpadding=0><tr bgcolor=#A4A4FF><td colspan=5><h3>CDRs not Processed Due to Errors</h3></td></tr><tr bgcolor=#A4A4FF><td colspan=5><h4>Ingress Carriers - CDRs with Duration > 0</h4></td></tr><tr bgcolor=#A4A4FF><td width=5%>#</td><td width=25%>Yr-Mon</td><td width=40%>Error</td><td width=10%>Calls</td><td width=20%>Minutes</td></tr> <tr><td>1</td><td>2007-07</td><td>Partner Node not Found.</td><td>1</td><td>2</td></tr> <tr><td>2</td><td>2007-08</td><td>IC Partner Destination not found.</td><td>4</td><td>1</td></tr> <tr><td>3</td><td> </td><td>Partner Node not Found.</td><td>11</td><td>9</td></tr> <tr><td>4</td><td>2007-09</td><td></td><td>278</td><td>50</td></tr> <tr><td>5</td><td>2007-10</td><td>IC Partner Destination not found.</td><td>7</td><td>5</td></tr> <tr><td>6</td><td> </td><td>Partner Node Rates not Found.</td><td>84</td><td>10</td></tr> <tr><td>7</td><td> </td><td>Partner Node not Found.</td><td>474</td><td>228</td></tr> <tr><td>8</td><td> </td><td></td><td>2087</td><td>5868</td></tr> <tr><td>9</td><td>2007-11</td><td>IC Partner Destination not found.</td><td>20</td><td>10</td></tr> <tr><td>10</td><td> </td><td>Partner Node Rates not Found.</td><td>32</td><td>37</td></tr> <tr><td>11</td><td> </td><td>Partner Node not Found.</td><td>371</td><td>437</td></tr> <tr><td>12</td><td> </td><td></td><td>907</td><td>1737</td></tr> <tr><td>13</td><td>2007-12</td><td>IC Partner Destination not found.</td><td>15</td><td>7</td></tr> <tr><td>14</td><td> </td><td>Partner Node Rates not Found.</td><td>7</td><td>21</td></tr> <tr><td>15</td><td> </td><td>Partner Node not Found.</td><td>610</td><td>612</td></tr> <tr><td>16</td><td> </td><td></td><td>88</td><td>105</td></tr> <tr><td>17</td><td>2008-01</td><td>IC Partner Destination not found.</td><td>38</td><td>51</td></tr> <tr><td>18</td><td> </td><td>Partner Node Rates not Found.</td><td>6</td><td>3</td></tr> <tr><td>19</td><td> </td><td>Partner Node not Found.</td><td>322</td><td>1915</td></tr> <tr><td>20</td><td> </td><td></td><td>19</td><td>76</td></tr> <tr><td>21</td><td>2008-02</td><td>IC Partner Destination not found.</td><td>19</td><td>22</td></tr> <tr><td>22</td><td> </td><td>Partner Node Rates not Found.</td><td>4</td><td>7</td></tr> <tr><td>23</td><td> </td><td>Partner Node not Found.</td><td>1</td><td>1</td></tr> <tr><td>24</td><td> </td><td></td><td>11</td><td>112</td></tr> <tr><td>25</td><td>2008-03</td><td>IC Partner Destination not found.</td><td>30</td><td>21</td></tr> <tr><td>26</td><td> </td><td>Partner Node Rates not Found.</td><td>2</td><td>2</td></tr> <tr><td>27</td><td> </td><td>Partner Node not Found.</td><td>5</td><td>14</td></tr> <tr><td>28</td><td> </td><td></td><td>31</td><td>138</td></tr> <tr><td>29</td><td>2008-04</td><td>IC Partner Destination not found.</td><td>30</td><td>22</td></tr> <tr><td>30</td><td> </td><td>Partner Node Rates not Found.</td><td>29</td><td>66</td></tr> <tr><td>31</td><td> </td><td>Partner Node not Found.</td><td>1804</td><td>2846</td></tr> <tr><td>32</td><td> </td><td></td><td>1230</td><td>1445</td></tr> <tr><td>33</td><td>2008-05</td><td>IC Partner Destination not found.</td><td>12</td><td>25</td></tr> <tr><td>34</td><td> </td><td>Partner Node Rates not Found.</td><td>29</td><td>80</td></tr> <tr><td>35</td><td> </td><td>Partner Node not Found.</td><td>6203</td><td>13004</td></tr> <tr><td>36</td><td> </td><td></td><td>2175</td><td>3777</td></tr> <tr><td>37</td><td>2008-06</td><td>IC Partner Destination not found.</td><td>390</td><td>1126</td></tr> <tr><td>38</td><td> </td><td>Partner Node Rates not Found.</td><td>26</td><td>64</td></tr> <tr><td>39</td><td> </td><td>Partner Node not Found.</td><td>7545</td><td>11332</td></tr> <tr><td>40</td><td> </td><td></td><td>1869</td><td>2253</td></tr> <tr><td>41</td><td>2008-07</td><td>IC Partner Destination not found.</td><td>632</td><td>3606</td></tr> <tr><td>42</td><td> </td><td>Partner Node not Found.</td><td>335</td><td>591</td></tr> <tr><td>43</td><td> </td><td></td><td>99</td><td>144</td></tr> <tr><td>44</td><td>2008-08</td><td>IC Partner Destination not found.</td><td>180</td><td>771</td></tr> <tr><td>45</td><td> </td><td>Partner Node Rates not Found.</td><td>45</td><td>255</td></tr> <tr><td>46</td><td> </td><td>Partner Node not Found.</td><td>19</td><td>66</td></tr> <tr><td>47</td><td> </td><td></td><td>28332</td><td>80725</td></tr> <tr><td>48</td><td>2008-09</td><td>IC Partner Destination not found.</td><td>129</td><td>1413</td></tr> <tr><td>49</td><td> </td><td>Partner Node Rates not Found.</td><td>41</td><td>202</td></tr> <tr><td>50</td><td> </td><td>Partner Node not Found.</td><td>1768</td><td>3980</td></tr> <tr><td>51</td><td> </td><td></td><td>6091</td><td>20143</td></tr> <tr><td>52</td><td>2008-10</td><td>IC Partner Destination not found.</td><td>220</td><td>1429</td></tr> <tr><td>53</td><td> </td><td>Partner Node Rates not Found.</td><td>56</td><td>419</td></tr> <tr><td>54</td><td> </td><td>Partner Node not Found.</td><td>5447</td><td>15201</td></tr> <tr><td>55</td><td> </td><td></td><td>2032</td><td>4203</td></tr> <tr><td>56</td><td>2008-11</td><td>IC Partner Destination not found.</td><td>43</td><td>244</td></tr> <tr><td>57</td><td> </td><td>Partner Node Rates not Found.</td><td>13</td><td>33</td></tr> <tr><td>58</td><td> </td><td>Partner Node not Found.</td><td>751</td><td>2774</td></tr> <tr><td>59</td><td> </td><td></td><td>127</td><td>214</td></tr></Table><br><Table align=Center width=600 border=1 cellspacing=0 cellpadding=0><tr bgcolor=#A4A4FF><td colspan=5><h3>CDRs not Processed Due to Errors</h3></td></tr><tr bgcolor=#A4A4FF><td colspan=5><h4>Egress Carriers - CDRs with Duration > 0</h4></td></tr><tr bgcolor=#A4A4FF><td width=5%>#</td><td width=25%>Yr-Mon</td><td width=40%>Error</td><td width=10%>Calls</td><td width=20%>Minutes</td></tr> <tr><td>1</td><td>2007-07</td><td></td><td>1</td><td>2</td></tr> <tr><td>2</td><td>2007-08</td><td></td><td>15</td><td>10</td></tr> <tr><td>3</td><td>2007-09</td><td></td><td>278</td><td>50</td></tr> <tr><td>4</td><td>2007-10</td><td>IC Partner Destination not found.</td><td>7</td><td>8</td></tr> <tr><td>5</td><td> </td><td>Partner Node Rates not Found.</td><td>140</td><td>22</td></tr> <tr><td>6</td><td> </td><td>Partner Node not Found.</td><td>438</td><td>152</td></tr> <tr><td>7</td><td> </td><td></td><td>2067</td><td>5929</td></tr> <tr><td>8</td><td>2007-11</td><td>IC Partner Destination not found.</td><td>20</td><td>26</td></tr> <tr><td>9</td><td> </td><td>Partner Node Rates not Found.</td><td>838</td><td>1673</td></tr> <tr><td>10</td><td> </td><td>Partner Node not Found.</td><td>111</td><td>69</td></tr> <tr><td>11</td><td> </td><td></td><td>361</td><td>452</td></tr> <tr><td>12</td><td>2007-12</td><td>IC Partner Destination not found.</td><td>16</td><td>66</td></tr> <tr><td>13</td><td> </td><td>Partner Node Rates not Found.</td><td>412</td><td>243</td></tr> <tr><td>14</td><td> </td><td>Partner Node not Found.</td><td>73</td><td>40</td></tr> <tr><td>15</td><td> </td><td></td><td>219</td><td>398</td></tr> <tr><td>16</td><td>2008-01</td><td>IC Partner Destination not found.</td><td>36</td><td>118</td></tr> <tr><td>17</td><td> </td><td>Partner Node Rates not Found.</td><td>251</td><td>1674</td></tr> <tr><td>18</td><td> </td><td></td><td>98</td><td>252</td></tr> <tr><td>19</td><td>2008-02</td><td>IC Partner Destination not found.</td><td>13</td><td>127</td></tr> <tr><td>20</td><td> </td><td>Partner Node Rates not Found.</td><td>1</td><td>1</td></tr> <tr><td>21</td><td> </td><td></td><td>21</td><td>14</td></tr> <tr><td>22</td><td>2008-03</td><td>IC Partner Destination not found.</td><td>43</td><td>161</td></tr> <tr><td>23</td><td> </td><td></td><td>25</td><td>13</td></tr> <tr><td>24</td><td>2008-04</td><td>IC Partner Destination not found.</td><td>93</td><td>169</td></tr> <tr><td>25</td><td> </td><td>Partner Node not Found.</td><td>1161</td><td>1298</td></tr> <tr><td>26</td><td> </td><td></td><td>1839</td><td>2912</td></tr> <tr><td>27</td><td>2008-05</td><td>IC Partner Destination not found.</td><td>52</td><td>110</td></tr> <tr><td>28</td><td> </td><td>Partner Node Rates not Found.</td><td>7</td><td>3</td></tr> <tr><td>29</td><td> </td><td>Partner Node not Found.</td><td>2149</td><td>5179</td></tr> <tr><td>30</td><td> </td><td></td><td>6211</td><td>11595</td></tr> <tr><td>31</td><td>2008-06</td><td>IC Partner Destination not found.</td><td>85</td><td>164</td></tr> <tr><td>32</td><td> </td><td>Partner Node Rates not Found.</td><td>19</td><td>55</td></tr> <tr><td>33</td><td> </td><td>Partner Node not Found.</td><td>1849</td><td>2208</td></tr> <tr><td>34</td><td> </td><td></td><td>7877</td><td>12347</td></tr> <tr><td>35</td><td>2008-07</td><td>IC Partner Destination not found.</td><td>82</td><td>277</td></tr> <tr><td>36</td><td> </td><td>Partner Node not Found.</td><td>259</td><td>364</td></tr> <tr><td>37</td><td> </td><td></td><td>725</td><td>3700</td></tr> <tr><td>38</td><td>2008-08</td><td>IC Partner Destination not found.</td><td>45</td><td>47</td></tr> <tr><td>39</td><td> </td><td>Partner Node not Found.</td><td>6</td><td>1</td></tr> <tr><td>40</td><td> </td><td></td><td>28525</td><td>81768</td></tr> <tr><td>41</td><td>2008-09</td><td>IC Partner Destination not found.</td><td>208</td><td>304</td></tr> <tr><td>42</td><td> </td><td></td><td>7821</td><td>25432</td></tr> <tr><td>43</td><td>2008-10</td><td>IC Partner Destination not found.</td><td>228</td><td>462</td></tr> <tr><td>44</td><td> </td><td>Partner Node not Found.</td><td>756</td><td>1249</td></tr> <tr><td>45</td><td> </td><td></td><td>6771</td><td>19540</td></tr> <tr><td>46</td><td>2008-11</td><td>IC Partner Destination not found.</td><td>11</td><td>12</td></tr> <tr><td>47</td><td> </td><td>Partner Node not Found.</td><td>144</td><td>224</td></tr> <tr><td>48</td><td> </td><td></td><td>779</td><td>3028</td></tr></Table><br><Table align=Center width=600 border=1 cellspacing=0 cellpadding=0><tr bgcolor=#A4A4FF><td colspan=5><h3>CDRs not Processed Due to Errors</h3></td></tr><tr bgcolor=#A4A4FF><td colspan=5><h4>Ingress Carriers - Zero Duration CDRs</h4></td></tr><tr bgcolor=#A4A4FF><td width=5%>#</td><td width=25%>Yr-Mon</td><td width=40%>Error</td><td width=10%>Calls</td><td width=20%>Minutes</td></tr> <tr><td>1</td><td>2007-07</td><td>IC Partner Destination not found.</td><td>1</td><td>0</td></tr> <tr><td>2</td><td> </td><td>Partner Node Rates not Found.</td><td>1</td><td>0</td></tr> <tr><td>3</td><td> </td><td>Partner Node not Found.</td><td>39</td><td>0</td></tr> <tr><td>4</td><td>2007-08</td><td>IC Partner Destination not found.</td><td>23</td><td>0</td></tr> <tr><td>5</td><td> </td><td>Partner Node Rates not Found.</td><td>22</td><td>0</td></tr> <tr><td>6</td><td> </td><td>Partner Node not Found.</td><td>235</td><td>0</td></tr> <tr><td>7</td><td> </td><td></td><td>11</td><td>0</td></tr> <tr><td>8</td><td>2007-09</td><td>IC Partner Destination not found.</td><td>61</td><td>0</td></tr> <tr><td>9</td><td> </td><td>Partner Node Rates not Found.</td><td>8</td><td>0</td></tr> <tr><td>10</td><td> </td><td>Partner Node not Found.</td><td>126</td><td>0</td></tr> <tr><td>11</td><td> </td><td></td><td>3413</td><td>0</td></tr> <tr><td>12</td><td>2007-10</td><td>IC Partner Destination not found.</td><td>3615</td><td>0</td></tr> <tr><td>13</td><td> </td><td>Partner Node Rates not Found.</td><td>84860</td><td>0</td></tr> <tr><td>14</td><td> </td><td>Partner Node not Found.</td><td>290</td><td>0</td></tr> <tr><td>15</td><td> </td><td></td><td>16135</td><td>0</td></tr> <tr><td>16</td><td>2007-11</td><td>IC Partner Destination not found.</td><td>6197</td><td>0</td></tr> <tr><td>17</td><td> </td><td>Partner Node Rates not Found.</td><td>476</td><td>0</td></tr> <tr><td>18</td><td> </td><td>Partner Node not Found.</td><td>542</td><td>0</td></tr> <tr><td>19</td><td> </td><td></td><td>2475</td><td>0</td></tr> <tr><td>20</td><td>2007-12</td><td>IC Partner Destination not found.</td><td>8981</td><td>0</td></tr> <tr><td>21</td><td> </td><td>Partner Node Rates not Found.</td><td>25</td><td>0</td></tr> <tr><td>22</td><td> </td><td>Partner Node not Found.</td><td>276</td><td>0</td></tr> <tr><td>23</td><td> </td><td></td><td>1546</td><td>0</td></tr> <tr><td>24</td><td>2008-01</td><td>IC Partner Destination not found.</td><td>9279</td><td>0</td></tr> <tr><td>25</td><td> </td><td>Partner Node Rates not Found.</td><td>20</td><td>0</td></tr> <tr><td>26</td><td> </td><td>Partner Node not Found.</td><td>56</td><td>0</td></tr> <tr><td>27</td><td> </td><td></td><td>1504</td><td>0</td></tr> <tr><td>28</td><td>2008-02</td><td>IC Partner Destination not found.</td><td>7517</td><td>0</td></tr> <tr><td>29</td><td> </td><td>Partner Node Rates not Found.</td><td>67</td><td>0</td></tr> <tr><td>30</td><td> </td><td>Partner Node not Found.</td><td>662</td><td>0</td></tr> <tr><td>31</td><td> </td><td></td><td>1709</td><td>0</td></tr> <tr><td>32</td><td>2008-03</td><td>IC Partner Destination not found.</td><td>9589</td><td>0</td></tr> <tr><td>33</td><td> </td><td>Partner Node Rates not Found.</td><td>39</td><td>0</td></tr> <tr><td>34</td><td> </td><td>Partner Node not Found.</td><td>305</td><td>0</td></tr> <tr><td>35</td><td> </td><td></td><td>1919</td><td>0</td></tr> <tr><td>36</td><td>2008-04</td><td>IC Partner Destination not found.</td><td>2755</td><td>0</td></tr> <tr><td>37</td><td> </td><td>Partner Node Rates not Found.</td><td>92</td><td>0</td></tr> <tr><td>38</td><td> </td><td>Partner Node not Found.</td><td>2227</td><td>0</td></tr> <tr><td>39</td><td> </td><td></td><td>3319</td><td>0</td></tr> <tr><td>40</td><td>2008-05</td><td>IC Partner Destination not found.</td><td>4071</td><td>0</td></tr> <tr><td>41</td><td> </td><td>Partner Node Rates not Found.</td><td>110</td><td>0</td></tr> <tr><td>42</td><td> </td><td>Partner Node not Found.</td><td>45293</td><td>0</td></tr> <tr><td>43</td><td> </td><td></td><td>2535</td><td>0</td></tr> <tr><td>44</td><td>2008-06</td><td>IC Partner Destination not found.</td><td>5091</td><td>0</td></tr> <tr><td>45</td><td> </td><td>Partner Node Rates not Found.</td><td>191</td><td>0</td></tr> <tr><td>46</td><td> </td><td>Partner Node not Found.</td><td>9600</td><td>0</td></tr> <tr><td>47</td><td> </td><td></td><td>3043</td><td>0</td></tr> <tr><td>48</td><td>2008-07</td><td>IC Partner Destination not found.</td><td>6027</td><td>0</td></tr> <tr><td>49</td><td> </td><td>Partner Node Rates not Found.</td><td>110</td><td>0</td></tr> <tr><td>50</td><td> </td><td>Partner Node not Found.</td><td>1107</td><td>0</td></tr> <tr><td>51</td><td> </td><td></td><td>5364</td><td>0</td></tr> <tr><td>52</td><td>2008-08</td><td>IC Partner Destination not found.</td><td>8553</td><td>0</td></tr> <tr><td>53</td><td> </td><td>Partner Node Rates not Found.</td><td>100</td><td>0</td></tr> <tr><td>54</td><td> </td><td>Partner Node not Found.</td><td>6</td><td>0</td></tr> <tr><td>55</td><td> </td><td></td><td>50489</td><td>0</td></tr> <tr><td>56</td><td>2008-09</td><td>IC Partner Destination not found.</td><td>4891</td><td>0</td></tr> <tr><td>57</td><td> </td><td>Partner Node Rates not Found.</td><td>129</td><td>0</td></tr> <tr><td>58</td><td> </td><td>Partner Node not Found.</td><td>1174</td><td>0</td></tr> <tr><td>59</td><td> </td><td></td><td>4635</td><td>0</td></tr> <tr><td>60</td><td>2008-10</td><td>IC Partner Destination not found.</td><td>4211</td><td>0</td></tr> <tr><td>61</td><td> </td><td>Partner Node Rates not Found.</td><td>120</td><td>0</td></tr> <tr><td>62</td><td> </td><td>Partner Node not Found.</td><td>4299</td><td>0</td></tr> <tr><td>63</td><td> </td><td></td><td>1897</td><td>0</td></tr> <tr><td>64</td><td>2008-11</td><td>IC Partner Destination not found.</td><td>484</td><td>0</td></tr> <tr><td>65</td><td> </td><td>Partner Node Rates not Found.</td><td>48</td><td>0</td></tr> <tr><td>66</td><td> </td><td>Partner Node not Found.</td><td>637</td><td>0</td></tr> <tr><td>67</td><td> </td><td></td><td>320</td><td>0</td></tr></Table><br><Table align=Center width=600 border=1 cellspacing=0 cellpadding=0><tr bgcolor=#A4A4FF><td colspan=5><h3>CDRs not Processed Due to Errors</h3></td></tr><tr bgcolor=#A4A4FF><td colspan=5><h4>Egress Carriers - Zero Duration CDRs</h4></td></tr><tr bgcolor=#A4A4FF><td width=5%>#</td><td width=25%>Yr-Mon</td><td width=40%>Error</td><td width=10%>Calls</td><td width=20%>Minutes</td></tr> <tr><td>1</td><td>2007-07</td><td>IC Partner Destination not found.</td><td>9</td><td>0</td></tr> <tr><td>2</td><td> </td><td>Partner Node Rates not Found.</td><td>31</td><td>0</td></tr> <tr><td>3</td><td> </td><td></td><td>1</td><td>0</td></tr> <tr><td>4</td><td>2007-08</td><td>IC Partner Destination not found.</td><td>45</td><td>0</td></tr> <tr><td>5</td><td> </td><td>Partner Node Rates not Found.</td><td>159</td><td>0</td></tr> <tr><td>6</td><td> </td><td>Partner Node not Found.</td><td>14</td><td>0</td></tr> <tr><td>7</td><td> </td><td></td><td>73</td><td>0</td></tr> <tr><td>8</td><td>2007-09</td><td>IC Partner Destination not found.</td><td>94</td><td>0</td></tr> <tr><td>9</td><td> </td><td>Partner Node Rates not Found.</td><td>562</td><td>0</td></tr> <tr><td>10</td><td> </td><td></td><td>2952</td><td>0</td></tr> <tr><td>11</td><td>2007-10</td><td>IC Partner Destination not found.</td><td>850</td><td>0</td></tr> <tr><td>12</td><td> </td><td>Partner Node Rates not Found.</td><td>86190</td><td>0</td></tr> <tr><td>13</td><td> </td><td>Partner Node not Found.</td><td>46</td><td>0</td></tr> <tr><td>14</td><td> </td><td></td><td>17814</td><td>0</td></tr> <tr><td>15</td><td>2007-11</td><td>IC Partner Destination not found.</td><td>1340</td><td>0</td></tr> <tr><td>16</td><td> </td><td>Partner Node Rates not Found.</td><td>2644</td><td>0</td></tr> <tr><td>17</td><td> </td><td>Partner Node not Found.</td><td>258</td><td>0</td></tr> <tr><td>18</td><td> </td><td></td><td>5448</td><td>0</td></tr> <tr><td>19</td><td>2007-12</td><td>IC Partner Destination not found.</td><td>1085</td><td>0</td></tr> <tr><td>20</td><td> </td><td>Partner Node Rates not Found.</td><td>1471</td><td>0</td></tr> <tr><td>21</td><td> </td><td>Partner Node not Found.</td><td>95</td><td>0</td></tr> <tr><td>22</td><td> </td><td></td><td>8177</td><td>0</td></tr> <tr><td>23</td><td>2008-01</td><td>IC Partner Destination not found.</td><td>496</td><td>0</td></tr> <tr><td>24</td><td> </td><td>Partner Node Rates not Found.</td><td>1487</td><td>0</td></tr> <tr><td>25</td><td> </td><td>Partner Node not Found.</td><td>1</td><td>0</td></tr> <tr><td>26</td><td> </td><td></td><td>8875</td><td>0</td></tr> <tr><td>27</td><td>2008-02</td><td>IC Partner Destination not found.</td><td>713</td><td>0</td></tr> <tr><td>28</td><td> </td><td>Partner Node Rates not Found.</td><td>1608</td><td>0</td></tr> <tr><td>29</td><td> </td><td>Partner Node not Found.</td><td>84</td><td>0</td></tr> <tr><td>30</td><td> </td><td></td><td>7550</td><td>0</td></tr> <tr><td>31</td><td>2008-03</td><td>IC Partner Destination not found.</td><td>469</td><td>0</td></tr> <tr><td>32</td><td> </td><td>Partner Node Rates not Found.</td><td>1797</td><td>0</td></tr> <tr><td>33</td><td> </td><td>Partner Node not Found.</td><td>63</td><td>0</td></tr> <tr><td>34</td><td> </td><td></td><td>9523</td><td>0</td></tr> <tr><td>35</td><td>2008-04</td><td>IC Partner Destination not found.</td><td>443</td><td>0</td></tr> <tr><td>36</td><td> </td><td>Partner Node Rates not Found.</td><td>2301</td><td>0</td></tr> <tr><td>37</td><td> </td><td>Partner Node not Found.</td><td>1862</td><td>0</td></tr> <tr><td>38</td><td> </td><td></td><td>3787</td><td>0</td></tr> <tr><td>39</td><td>2008-05</td><td>IC Partner Destination not found.</td><td>525</td><td>0</td></tr> <tr><td>40</td><td> </td><td>Partner Node Rates not Found.</td><td>1875</td><td>0</td></tr> <tr><td>41</td><td> </td><td>Partner Node not Found.</td><td>35440</td><td>0</td></tr> <tr><td>42</td><td> </td><td></td><td>14169</td><td>0</td></tr> <tr><td>43</td><td>2008-06</td><td>IC Partner Destination not found.</td><td>528</td><td>0</td></tr> <tr><td>44</td><td> </td><td>Partner Node Rates not Found.</td><td>2559</td><td>0</td></tr> <tr><td>45</td><td> </td><td>Partner Node not Found.</td><td>759</td><td>0</td></tr> <tr><td>46</td><td> </td><td></td><td>14079</td><td>0</td></tr> <tr><td>47</td><td>2008-07</td><td>IC Partner Destination not found.</td><td>402</td><td>0</td></tr> <tr><td>48</td><td> </td><td>Partner Node Rates not Found.</td><td>784</td><td>0</td></tr> <tr><td>49</td><td> </td><td>Partner Node not Found.</td><td>1806</td><td>0</td></tr> <tr><td>50</td><td> </td><td></td><td>9616</td><td>0</td></tr> <tr><td>51</td><td>2008-08</td><td>IC Partner Destination not found.</td><td>110</td><td>0</td></tr> <tr><td>52</td><td> </td><td>Partner Node Rates not Found.</td><td>1203</td><td>0</td></tr> <tr><td>53</td><td> </td><td>Partner Node not Found.</td><td>14</td><td>0</td></tr> <tr><td>54</td><td> </td><td></td><td>57821</td><td>0</td></tr> <tr><td>55</td><td>2008-09</td><td>IC Partner Destination not found.</td><td>92</td><td>0</td></tr> <tr><td>56</td><td> </td><td>Partner Node Rates not Found.</td><td>667</td><td>0</td></tr> <tr><td>57</td><td> </td><td>Partner Node not Found.</td><td>14</td><td>0</td></tr> <tr><td>58</td><td> </td><td></td><td>10056</td><td>0</td></tr> <tr><td>59</td><td>2008-10</td><td>IC Partner Destination not found.</td><td>150</td><td>0</td></tr> <tr><td>60</td><td> </td><td>Partner Node Rates not Found.</td><td>928</td><td>0</td></tr> <tr><td>61</td><td> </td><td>Partner Node not Found.</td><td>837</td><td>0</td></tr> <tr><td>62</td><td> </td><td></td><td>8612</td><td>0</td></tr> <tr><td>63</td><td>2008-11</td><td>IC Partner Destination not found.</td><td>21</td><td>0</td></tr> <tr><td>64</td><td> </td><td>Partner Node Rates not Found.</td><td>178</td><td>0</td></tr> <tr><td>65</td><td> </td><td>Partner Node not Found.</td><td>163</td><td>0</td></tr> <tr><td>66</td><td> </td><td></td><td>1127</td><td>0</td></tr></Table><br><Table align=Center width=600 border=1 cellspacing=0 cellpadding=0><tr bgcolor=#A4A4FF><td colspan=6><h3>Miss-Configured Carriers</h3></td></tr><tr bgcolor=#A4A4FF><td width=5%>#</td><td width=25%>Carrier Trunk</td><td width=10%>Calls</td><td width=20%>Minutes</td><td width=20%>First Call Time</td><td width=20%>Last Call Time</td></tr> <tr><td colspan=6 >No Record Found</td></tr></Table><br><b> This email is auto-generated by Terminus Customer Care & Billing System</b></Body></Html>',1)";
 			System.out.println("SQL : "+sql);
			update=stmt.executeUpdate(sql);
		}catch (SQLException sq){
 			System.out.println("SQL Exception :"+sq.getMessage());
 		}
 		return update;
	}
	
	private String applyStyleSheet(String message, String stylesheet) throws
    TransformerConfigurationException, TransformerException, IOException {
		if (stylesheet.length() == 0)
			return message;
	    StringWriter fw = new StringWriter();
	
	    Xml2Text xml2Text = new Xml2Text(new PrintWriter(fw));
	
	    WhiteSpaceFilter whitespaceFilter = new WhiteSpaceFilter();
	
	    whitespaceFilter.setContentHandler(xml2Text);
	
	    AsciiFilter asciiFilter = new AsciiFilter();
	
	    asciiFilter.setContentHandler(whitespaceFilter);
	
	    TransformerFactory factory = TransformerFactory.newInstance();
	
	    FileWriter fw1 = new FileWriter("tmp.txt");
	    fw1.write(message);
	    fw1.close();
	
	    Transformer transformer = factory.newTransformer(new StreamSource(new File("stylesheets/"+stylesheet)));
	
	    transformer.transform(new StreamSource(new File("tmp.txt")),
	                          new SAXResult(asciiFilter));
	
	    return fw.toString();
  }
	


 }
